---
- hosts: pi-top
  remote_user: root
  gather_facts: no

  pre_tasks:
    - name: Install python2 dependency for ansible
      raw: apt-get update; apt-get -y install  python-simplejson

  roles: 
  - system
    #- kde
