---
- hosts: pi-top
  remote_user: root
  gather_facts: no
  vars:
   SSID: [put your ssid here]
   wpa_password: [put your wifi password here]
   hostname: pi-top
   username: pi-top
   userpassword: pi-top
   keypath: config/ssh_keys/id_dsa.pub

  pre_tasks:
    - name: Install python2 dependency for ansible
      raw: apt-get -y install  python-simplejson

  tasks:


  - name:  Bootstrap apt-get and install aptitude
    apt: update_cache=yes name=aptitude state=present

  - name: Set ssh keys root account
    authorized_key: user=root key="{{ lookup('file', '{{keypath}}') }}"
  
  - name: Create new user {{username}}
    shell: adduser pi-top creates=/home/{{username}}

  - name: Add user {{username}} to groups
    user: name={{username}} groups=sudo,audio,video,bluetooth

  - name: Set {{username}} password to {{userpassword}}
    shell: echo {{username}}:{{userpassword}} | chpasswd
 

  - name: Disable ssh password authentication
    lineinfile: dest=/etc/ssh/sshd_config line="PasswordAuthentication no"

  - name: Install vim
    apt: name=vim state=present

  - name: Install raspi-config, rpi-update, vim, rsync
    apt: name={{item}} state=present
    with_items:
    - raspi-config
    - rpi-update
    - rsync
    - vim
    - rsync

  - name: Resize partition
    command: raspi-config --expand-rootfs

  - name: Reboot {{ inventory_hostname }}
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true

  - name: Waiting for {{ inventory_hostname }} to come back 
    local_action: wait_for host={{ inventory_hostname }} state=started port=22
    sudo: false


  - name: Device {{ inventory_hostname }} wake up and running ! Upgrading all the system to latest
    apt: upgrade=yes

  - name: Install NTP
    apt: name=ntp state=present    

  - name: Start NTP Service
    service: name=ntp state=started enabled=yes
  
  - name : Change hostname to {{hostname}}
    hostname: name={{hostname}}

  - name: install iptables
    apt: name=iptables state=present

  - name: install wifi related packages
    apt: name={{item}} state=present
    with_items:
    - firmware-ralink
    - firmware-realtek
    - firmware-atheros
    - firmware-brcm80211
    - wireless-tools
    - wpasupplicant

  - name: Configure dhcp on wlan0 and eth0
    template: src=config/etc/network/interfaces-eth0-dhcp-wlan0-dhcp dest=/etc/network/interfaces

  - name: Configure wpasupplicant
    template: src=config/etc/wpa_supplicant/wpa_supplicant.conf.template dest=/etc/wpa_supplicant/wpa_supplicant.conf


  - name: Restart network services
    service: name={{item}} state=restarted
    with_items:
    - networking

  - name: Install Avahi
    apt: name=avahi-daemon state=present

  - name: Start Avahi service
    service: name=avahi-daemon state=started enabled=yes




  - name: Lock root account. From now on you will log in login as {{hostname}}/{{hostname}}
    command: /usr/bin/passwd -l root

  - name: Reboot {{ inventory_hostname }}
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true

