---
-  name : Install KDE. This will take some time (~30 min)
   apt: name=kde-full state=present

- name: Configure color depth
  lineinfile: dest=/boot/config.txt line="framebuffer_depth=32"
   


- name: Reboot {{ inventory_hostname }}
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Waiting for {{ inventory_hostname }} to come back 
  local_action: wait_for host={{ inventory_hostname }} state=started port=22
  sudo: false